/* Automatically generated by wasm2c */
#ifndef GLICOL_CPP_H_GENERATED_
#define GLICOL_CPP_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;

typedef struct w2c_glicol__wasm {
  struct w2c_env* w2c_env_instance;
  u32 w2c_0x5F_stack_pointer;
  u32 w2c_0x5F_data_end;
  u32 w2c_0x5F_heap_base;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_glicol__wasm;

void wasm2c_glicol__wasm_instantiate(w2c_glicol__wasm*, struct w2c_env*);
void wasm2c_glicol__wasm_free(w2c_glicol__wasm*);
wasm_rt_func_type_t wasm2c_glicol__wasm_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'now' */
f64 w2c_env_now(struct w2c_env*);

/* export: 'memory' */
wasm_rt_memory_t* w2c_glicol__wasm_memory(w2c_glicol__wasm* instance);

/* export: 'alloc_u8' */
u32 w2c_glicol__wasm_alloc_u8(w2c_glicol__wasm*, u32);

/* export: 'dealloc_u8' */
void w2c_glicol__wasm_dealloc_u8(w2c_glicol__wasm*, u32, u32);

/* export: 'process' */
void w2c_glicol__wasm_process(w2c_glicol__wasm*, u32, u32, u32);

/* export: 'add_sample' */
void w2c_glicol__wasm_add_sample(w2c_glicol__wasm*, u32, u32, u32, u32, u32);

/* export: 'update' */
void w2c_glicol__wasm_update(w2c_glicol__wasm*, u32);

/* export: 'send_msg' */
void w2c_glicol__wasm_send_msg(w2c_glicol__wasm*, u32);

/* export: 'live_coding_mode' */
void w2c_glicol__wasm_live_coding_mode(w2c_glicol__wasm*, u32);

/* export: 'set_bpm' */
void w2c_glicol__wasm_set_bpm(w2c_glicol__wasm*, f32);

/* export: 'set_track_amp' */
void w2c_glicol__wasm_set_track_amp(w2c_glicol__wasm*, f32);

/* export: 'set_sr' */
void w2c_glicol__wasm_set_sr(w2c_glicol__wasm*, f32);

/* export: 'set_seed' */
void w2c_glicol__wasm_set_seed(w2c_glicol__wasm*, f32);

/* export: 'reset' */
void w2c_glicol__wasm_reset(w2c_glicol__wasm*);

/* export: '__data_end' */
u32* w2c_glicol__wasm_0x5F_data_end(w2c_glicol__wasm* instance);

/* export: '__heap_base' */
u32* w2c_glicol__wasm_0x5F_heap_base(w2c_glicol__wasm* instance);

#ifdef __cplusplus
}
#endif

#endif  /* GLICOL_CPP_H_GENERATED_ */
