[package]
name = "gd_json_converter"
version.workspace = true
edition.workspace = true

[dependencies]
json5 = "0.4"
serde_json = "1"
toml = "0.8"
serde_yaml = { git = "https://github.com/dtolnay/serde-yaml" }
cxx = { workspace = true }
